# Generated by Django 2.2.7 on 2019-12-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "votes_collected",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Počet sesbíraných hlasů"
                    ),
                ),
                (
                    "votes_targeted",
                    models.PositiveIntegerField(
                        default=8000, verbose_name="Cílový počet sesbíraných hlasů"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.Site"
                    ),
                ),
            ],
        ),
    ]
